services:
  - type: web
    name: ledgeman-backend
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn server:app --workers 2 --bind 0.0.0.0:$PORT --timeout 120
    envVars:
      - key: SUPERADMIN_KEY
        value: 3ef8b91db2faf7689bdde85374b34190f99e57bbb338de7d087f673a99f9d2ce
      - key: JWT_SECRET
        value: 7cc22cfeaec5ddf2da83bc656ec1fa079005ad3bdf7efaac8cb75f8298a21eee
      - key: DATABASE_PATH
        value: /data/ledgeman.db
    disk:
      name: ledgeman-data
      mountPath: /data
      sizeGB: 1
