services:
  - type: web
    name: ledgerman-frontend
    env: static
    buildCommand: ""
    startCommand: ""
    staticPublishPath: ./ledgerman/app
    envVars:
      - key: NODE_ENV
        value: production
    customDomains:
      - name: ledgerman.org
